[package]
name = "alab-live"
version = "0.1.0"
edition = "2024"

[dependencies]

[workspace]
members = [ 
    "session1/authentication",
    "session1/hello_world",
    "session1/login", "session1/login_manager",
    "session1/variables",
]
