[package]
name = "file_adapt"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
pin-project-lite = "0.2.16"
tokio = { version = "1.47.1", features = ["full"] }
tokio-stream = { version = "0.1.17", features = ["full"] }
tokio-util = { version = "0.7.16", features = ["io"] }
