[package]
name = "collector"
version = "0.1.0"
edition = "2024"

[dependencies]
shared_data ={ path = "../shared_data" }
sysinfo = { version = "0.36.1", features = ["apple-app-store"] }
thiserror = "2.0.15"
uuid = { version = "1.18.0", features = ["v4", "fast-rng"] }
